Repository knights-dev/knights, pull requests merged in 2020-02, with the labels that each got.

#30 ノードエディタで平行移動・拡大縮小ができるようにした
  workspaces/editor/package.json
  workspaces/editor/src/components/Editor.tsx
  yarn.lock
Labels: S-waiting-for-review

#35 インタプリタ内部のロジックを記述するためのクレートを追加
  .gitignore
  Cargo.lock
  Cargo.toml
  workspaces/editor/src/bootstrap.tsx
  workspaces/editor/webpack.config.js
  workspaces/interp-core/Cargo.lock
  workspaces/interp-core/Cargo.toml
  workspaces/interp-core/src/lib.rs
  workspaces/interp-if/.cargo/config
  workspaces/interp-if/Cargo.lock
  workspaces/interp-if/Cargo.toml
  workspaces/interp-if/src/lib.rs
  workspaces/interp-rs/.gitignore
Labels: A-interpreter, S-waiting-for-review

#39 CONTRIBUTING.md を追加
  CONTRIBUTING.md
Labels: S-waiting-for-review

#43 wasm-packを依存に追加
  workspaces/editor/package.json
  yarn.lock
Labels: S-waiting-for-review

#52 CI で Rust のコードについてもフォーマットをチェックするようにした
  .github/workflows/lint.yml
  workspaces/interp-if/src/lib.rs
Labels: S-waiting-for-review

#49 Add absolute imports
  workspaces/editor/tsconfig.json
  workspaces/editor/webpack.config.js
Labels: A-node-editor

#53 Add issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/design_doc.md
  .github/ISSUE_TEMPLATE/suggestion.md
Labels: S-waiting-for-review

#61 eslint が absolute import だけでグルーピングするようにした
  workspaces/editor/.eslintrc.js
Labels: A-node-editor, S-waiting-for-review

#57 :building_construction: Make AST, values and types temporary
  Cargo.lock
  Cargo.toml
  workspaces/interp-types/Cargo.lock
  workspaces/interp-types/Cargo.toml
  workspaces/interp-types/src/lib.rs
Labels: A-interpreter, S-waiting-for-review

#56 Shift押しながらドラッグで全体を移動(パン)
  workspaces/editor/src/components/Editor.tsx
Labels: A-node-editor, S-waiting-for-review

#77 About wasm-pack for Windows
  README.md
Labels: S-waiting-for-review

#79 リポジトリ / ラベルの管理方針の変更に伴って CONTRIBUTING.md の文言を修正
  CONTRIBUTING.md
Labels: S-waiting-for-review

#74 :alembic: Fix AST
  workspaces/interp-types/src/lib.rs
Labels: S-waiting-for-review

#51 Feature/draw graph
  workspaces/editor/src/components/ArrowLayer.tsx
  workspaces/editor/src/components/Editor.tsx
  workspaces/editor/src/components/NodesLayer.tsx
  workspaces/editor/src/components/nodes/ApplyNode.tsx
  workspaces/editor/src/components/nodes/ArrowLine.tsx
  workspaces/editor/src/components/nodes/CurvedArrowLine.tsx
  workspaces/editor/src/components/nodes/DoubleCurvedArrowLine.tsx
  workspaces/editor/src/components/nodes/IONode.tsx
  workspaces/editor/src/components/nodes/PatternNode.tsx
  workspaces/editor/src/components/nodes/ValueNode.tsx
  workspaces/editor/src/components/nodes/index.ts
  workspaces/editor/src/components/struct.ts
Labels: A-node-editor, S-waiting-for-review

#83 Rust クレートのテストを実行するジョブを追加
  .github/workflows/lint.yml
  .github/workflows/rust.yml
Labels: A-interpreter, S-waiting-for-review

#85 Pull Request テンプレートを追加
  .github/PULL_REQUEST_TEMPLATE.md
Labels: S-waiting-for-review

#82 object style ではなく string style を用いて CSS を記述するように修正
  workspaces/editor/.stylelintrc.js
  workspaces/editor/src/components/AppRoot.tsx
Labels: A-node-editor, S-waiting-for-review

#86 Move interp-type into interp-core
  Cargo.lock
  Cargo.toml
  workspaces/interp-core/src/lib.rs
  workspaces/interp-core/src/syntax.rs
  workspaces/interp-types/Cargo.lock
  workspaces/interp-types/Cargo.toml
Labels: S-waiting-for-review

#89 動作確認に使用している Rust のバージョンについて追記
  README.md
Labels: S-waiting-for-review

#91 Darafts of interp-core
  workspaces/interp-core/src/error.rs
  workspaces/interp-core/src/lib.rs
  workspaces/interp-core/src/reduction.rs
  workspaces/interp-core/src/syntax.rs
  workspaces/interp-core/src/typing.rs
Labels: A-interpreter, S-waiting-for-review
